// BRAWLMON — dados dos 65 brawlers + 18 tipos
// Gerado para Gustavo 5ºA, João 5ºA e Enzo 5ºB

const TIPOS = {
  eletrico:  { nome: "Elétrico", cor: "#FFD21F" },
  fogo:      { nome: "Fogo",     cor: "#FF4B1F" },
  agua:      { nome: "Água",      cor: "#1E9CFF" },
  planta:    { nome: "Planta",    cor: "#37D67A" },
  inseto:    { nome: "Inseto",    cor: "#9ACD32" },
  venenoso:  { nome: "Venenoso",  cor: "#9B30FF" },
  gelo:      { nome: "Gelo",      cor: "#7FDBFF" },
  fantasma:  { nome: "Fantasma",  cor: "#7B61FF" },
  fada:      { nome: "Fada",      cor: "#FF6EC7" },
  dragao:    { nome: "Dragão",    cor: "#E3350D" },
  aco:       { nome: "Aço",       cor: "#9AA5B1" },
  voador:    { nome: "Voador",    cor: "#6EC6FF" },
  psiquico:  { nome: "Psíquico",  cor: "#FF3E8A" },
  terrestre: { nome: "Terrestre", cor: "#D2691E" },
  pedra:     { nome: "Pedra",     cor: "#A1887F" },
  sombrio:   { nome: "Sombrio",   cor: "#3A3A4D" },
  lutador:   { nome: "Lutador",   cor: "#E53935" },
  normal:    { nome: "Normal",    cor: "#BDBDBD" },
};

// id, nome, tipo, vida, ataque, super, efeitoSuper, velocidade, cor, arma
// efeitoSuper: dano | cura | escudo | explosao | congelar | rapido
const BRAWLERS = [
  { id: 0,  nome: "Volt",      tipo: "eletrico", vida: 3400, ataque: 520, arma: "Raio Blaster",      super: "Tempestade Volt",   efeito: "dano",     superDano: 1500, velocidade: 1.15, cor: "#FFD21F" },
  { id: 1,  nome: "Labareda",  tipo: "fogo",     vida: 3800, ataque: 600, arma: "Lança-Chamas",       super: "Erupção Final",     efeito: "explosao", superDano: 1800, velocidade: 1.05, cor: "#FF4B1F" },
  { id: 2,  nome: "Maré",      tipo: "agua",     vida: 4200, ataque: 480, arma: "Jato d'Água",        super: "Tsunami",           efeito: "dano",     superDano: 1400, velocidade: 1.0,  cor: "#1E9CFF" },
  { id: 3,  nome: "Cipó",      tipo: "planta",   vida: 4600, ataque: 440, arma: "Chicote Vinha",      super: "Floresta Viva",     efeito: "cura",     superDano: 1200, velocidade: 0.95, cor: "#37D67A" },
  { id: 4,  nome: "Besouro",   tipo: "inseto",   vida: 3600, ataque: 560, arma: "Ferrão Duplo",       super: "Enxame Furioso",    efeito: "rapido",   superDano: 1300, velocidade: 1.25, cor: "#9ACD32" },
  { id: 5,  nome: "Peçonha",   tipo: "venenoso", vida: 3200, ataque: 620, arma: "Agulha Tóxica",      super: "Nuvem Venenosa",    efeito: "dano",     superDano: 1600, velocidade: 1.1,  cor: "#9B30FF" },
  { id: 6,  nome: "Nevasca",   tipo: "gelo",     vida: 4000, ataque: 500, arma: "Cristal de Gelo",    super: "Zero Absoluto",     efeito: "congelar", superDano: 1300, velocidade: 1.0,  cor: "#7FDBFF" },
  { id: 7,  nome: "Sombra",    tipo: "fantasma", vida: 3000, ataque: 680, arma: "Garra Sombria",      super: "Possessão",         efeito: "dano",     superDano: 1700, velocidade: 1.2,  cor: "#7B61FF" },
  { id: 8,  nome: "Lumia",     tipo: "fada",     vida: 3300, ataque: 540, arma: "Varinha Mágica",     super: "Encanto Lunar",     efeito: "cura",     superDano: 1100, velocidade: 1.1,  cor: "#FF6EC7" },
  { id: 9,  nome: "Draco",     tipo: "dragao",   vida: 5600, ataque: 700, arma: "Sopro Dracônico",    super: "Fúria do Dragão",   efeito: "explosao", superDano: 2200, velocidade: 0.95, cor: "#E3350D" },
  { id: 10, nome: "Ferrão",    tipo: "aco",      vida: 6200, ataque: 480, arma: "Punho de Aço",       super: "Muralha de Ferro",  efeito: "escudo",   superDano: 900,  velocidade: 0.85, cor: "#9AA5B1" },
  { id: 11, nome: "Vendaval",  tipo: "voador",   vida: 3100, ataque: 580, arma: "Asa Cortante",       super: "Tornado Supremo",   efeito: "dano",     superDano: 1500, velocidade: 1.35, cor: "#6EC6FF" },
  { id: 12, nome: "Mente",     tipo: "psiquico", vida: 2900, ataque: 660, arma: "Onda Mental",        super: "Explosão Psíquica", efeito: "dano",     superDano: 1750, velocidade: 1.05, cor: "#FF3E8A" },
  { id: 13, nome: "Duna",      tipo: "terrestre",vida: 5000, ataque: 520, arma: "Pá Sísmica",          super: "Terremoto",         efeito: "explosao", superDano: 1600, velocidade: 0.9,  cor: "#D2691E" },
  { id: 14, nome: "Rocha",     tipo: "pedra",    vida: 6400, ataque: 460, arma: "Pedregulho",         super: "Avalanche",         efeito: "escudo",   superDano: 1100, velocidade: 0.8,  cor: "#A1887F" },
  { id: 15, nome: "Noturno",   tipo: "sombrio",  vida: 3500, ataque: 640, arma: "Adaga Negra",        super: "Eclipse Total",     efeito: "dano",     superDano: 1800, velocidade: 1.15, cor: "#3A3A4D" },
  { id: 16, nome: "Soco",      tipo: "lutador",  vida: 4800, ataque: 620, arma: "Luvas de Luta",      super: "Combo Meteoro",     efeito: "dano",     superDano: 1650, velocidade: 1.0,  cor: "#E53935" },
  { id: 17, nome: "Bidu",      tipo: "normal",   vida: 4000, ataque: 500, arma: "Estilingue",         super: "Golpe Neutro",      efeito: "dano",     superDano: 1300, velocidade: 1.05, cor: "#BDBDBD" },
  { id: 18, nome: "Trovão",    tipo: "eletrico", vida: 3600, ataque: 600, arma: "Bobina Tesla",       super: "Raio Colossal",     efeito: "dano",     superDano: 1700, velocidade: 1.1,  cor: "#FFE14D" },
  { id: 19, nome: "Brasa",     tipo: "fogo",     vida: 3500, ataque: 640, arma: "Bumerangue Ígneo",   super: "Anel de Fogo",      efeito: "explosao", superDano: 1750, velocidade: 1.1,  cor: "#FF7043" },
  { id: 20, nome: "Onda",      tipo: "agua",     vida: 4400, ataque: 520, arma: "Tridente",           super: "Redemoinho",        efeito: "congelar", superDano: 1350, velocidade: 1.0,  cor: "#29B6F6" },
  { id: 21, nome: "Selva",     tipo: "planta",   vida: 5200, ataque: 470, arma: "Folha Navalha",      super: "Esporos Gigantes",  efeito: "cura",     superDano: 1000, velocidade: 0.9,  cor: "#66BB6A" },
  { id: 22, nome: "Vespa",     tipo: "inseto",   vida: 2800, ataque: 700, arma: "Ferrão Voador",      super: "Picada Mortal",     efeito: "rapido",   superDano: 1600, velocidade: 1.4,  cor: "#C0CA33" },
  { id: 23, nome: "Cobra",     tipo: "venenoso", vida: 3400, ataque: 610, arma: "Presas Ácidas",      super: "Bote Venenoso",     efeito: "dano",     superDano: 1650, velocidade: 1.15, cor: "#AB47BC" },
  { id: 24, nome: "Glacial",   tipo: "gelo",     vida: 4700, ataque: 530, arma: "Lança de Neve",      super: "Neve Eterna",       efeito: "congelar", superDano: 1400, velocidade: 0.95, cor: "#B3E5FC" },
  { id: 25, nome: "Espectro",  tipo: "fantasma", vida: 3200, ataque: 670, arma: "Correntes",          super: "Grito do Além",     efeito: "dano",     superDano: 1750, velocidade: 1.1,  cor: "#9575CD" },
  { id: 26, nome: "Fadinha",   tipo: "fada",     vida: 3000, ataque: 560, arma: "Pó de Fada",         super: "Desejo Final",      efeito: "cura",     superDano: 1400, velocidade: 1.2,  cor: "#F48FB1" },
  { id: 27, nome: "Brasagon",  tipo: "dragao",   vida: 6000, ataque: 750, arma: "Cauda Flamejante",   super: "Julgamento Dracônico", efeito: "explosao", superDano: 2400, velocidade: 0.9, cor: "#C62828" },
  { id: 28, nome: "Titanio",   tipo: "aco",      vida: 6800, ataque: 500, arma: "Marreta",            super: "Armadura Total",    efeito: "escudo",   superDano: 1000, velocidade: 0.8,  cor: "#B0BEC5" },
  { id: 29, nome: "Falcao",    tipo: "voador",   vida: 3300, ataque: 600, arma: "Bico Perfurante",    super: "Mergulho Celeste",  efeito: "dano",     superDano: 1600, velocidade: 1.3,  cor: "#4FC3F7" },
  { id: 30, nome: "Hipno",     tipo: "psiquico", vida: 3100, ataque: 640, arma: "Colher Psíquica",    super: "Controle Mental",   efeito: "congelar", superDano: 1500, velocidade: 1.05, cor: "#EC407A" },
  { id: 31, nome: "Tatu",      tipo: "terrestre",vida: 5400, ataque: 500, arma: "Garras de Terra",    super: "Fenda Sísmica",     efeito: "explosao", superDano: 1550, velocidade: 0.9,  cor: "#A1887F" },
  { id: 32, nome: "Granito",   tipo: "pedra",    vida: 6600, ataque: 520, arma: "Rocha Giratória",    super: "Meteoro Rochoso",   efeito: "explosao", superDano: 1700, velocidade: 0.8,  cor: "#8D6E63" },
  { id: 33, nome: "Umbra",     tipo: "sombrio",  vida: 3700, ataque: 660, arma: "Foice Negra",        super: "Noite Infinita",    efeito: "dano",     superDano: 1850, velocidade: 1.1,  cor: "#21212B" },
  { id: 34, nome: "Karate",    tipo: "lutador",  vida: 5000, ataque: 650, arma: "Faixa Preta",        super: "Soco do Tigre",     efeito: "dano",     superDano: 1800, velocidade: 1.0,  cor: "#EF5350" },
  { id: 35, nome: "Totó",      tipo: "normal",   vida: 4300, ataque: 520, arma: "Osso Mágico",        super: "Hiper Voz",         efeito: "dano",     superDano: 1350, velocidade: 1.0,  cor: "#D7CCC8" },
  { id: 36, nome: "Pilha",     tipo: "eletrico", vida: 3900, ataque: 560, arma: "Choque Duplo",       super: "Sobrecarga",        efeito: "rapido",   superDano: 1450, velocidade: 1.05, cor: "#FFCA28" },
  { id: 37, nome: "Vulcão",    tipo: "fogo",     vida: 5800, ataque: 680, arma: "Magma",              super: "Erupção Vulcânica", efeito: "explosao", superDano: 2100, velocidade: 0.85, cor: "#FF5722" },
  { id: 38, nome: "Bolha",     tipo: "agua",     vida: 3700, ataque: 550, arma: "Bolhas",             super: "Dilúvio",           efeito: "cura",     superDano: 1200, velocidade: 1.1,  cor: "#4DD0E1" },
  { id: 39, nome: "Cacto",     tipo: "planta",   vida: 4900, ataque: 590, arma: "Espinhos",           super: "Deserto Florido",   efeito: "dano",     superDano: 1500, velocidade: 0.95, cor: "#43A047" },
  { id: 40, nome: "Formiga",   tipo: "inseto",   vida: 4100, ataque: 540, arma: "Mandíbula",          super: "Colônia Gigante",   efeito: "escudo",   superDano: 1100, velocidade: 1.1,  cor: "#AFB42B" },
  { id: 41, nome: "Sapo",      tipo: "venenoso", vida: 4500, ataque: 570, arma: "Língua Ácida",       super: "Poça Tóxica",       efeito: "dano",     superDano: 1550, velocidade: 1.0,  cor: "#7B1FA2" },
  { id: 42, nome: "Pingu",     tipo: "gelo",     vida: 3800, ataque: 560, arma: "Peixe Congelado",    super: "Ventania Polar",    efeito: "congelar", superDano: 1450, velocidade: 1.05, cor: "#81D4FA" },
  { id: 43, nome: "Fantasmim", tipo: "fantasma", vida: 2900, ataque: 700, arma: "Lençol Assustador",  super: "Susto Mortal",      efeito: "dano",     superDano: 1800, velocidade: 1.2,  cor: "#5C6BC0" },
  { id: 44, nome: "Estrela",   tipo: "fada",     vida: 3400, ataque: 580, arma: "Cetro Brilhante",    super: "Chuva de Estrelas", efeito: "dano",     superDano: 1600, velocidade: 1.1,  cor: "#F06292" },
  { id: 45, nome: "Alado",     tipo: "dragao",   vida: 5400, ataque: 690, arma: "Asas de Fogo",       super: "Ira Ancestral",     efeito: "explosao", superDano: 2150, velocidade: 1.0,  cor: "#D32F2F" },
  { id: 46, nome: "Parafuso",  tipo: "aco",      vida: 6000, ataque: 540, arma: "Serra Circular",     super: "Blindagem Máxima",  efeito: "escudo",   superDano: 1000, velocidade: 0.85, cor: "#90A4AE" },
  { id: 47, nome: "Andorinha", tipo: "voador",   vida: 3000, ataque: 620, arma: "Penas Navalha",      super: "Rasante Furioso",   efeito: "rapido",   superDano: 1500, velocidade: 1.35, cor: "#81D4FA" },
  { id: 48, nome: "Oráculo",   tipo: "psiquico", vida: 3300, ataque: 680, arma: "Cristal Mental",     super: "Visão do Futuro",   efeito: "dano",     superDano: 1800, velocidade: 1.0,  cor: "#AD1457" },
  { id: 49, nome: "Minhoca",   tipo: "terrestre",vida: 4700, ataque: 510, arma: "Broca",              super: "Túnel Sem Fim",     efeito: "rapido",   superDano: 1300, velocidade: 1.0,  cor: "#BCAAA4" },
  { id: 50, nome: "Seixo",     tipo: "pedra",    vida: 5800, ataque: 560, arma: "Estilingue de Pedra",super: "Terremoto Rochoso", efeito: "explosao", superDano: 1600, velocidade: 0.85, cor: "#795548" },
  { id: 51, nome: "Corvo",     tipo: "sombrio",  vida: 3200, ataque: 670, arma: "Bico Sombrio",       super: "Céu Negro",         efeito: "dano",     superDano: 1750, velocidade: 1.2,  cor: "#30303D" },
  { id: 52, nome: "Boxe",      tipo: "lutador",  vida: 5200, ataque: 660, arma: "Luvas Vermelhas",    super: "Nocaute Supremo",   efeito: "dano",     superDano: 1900, velocidade: 1.0,  cor: "#C62828" },
  { id: 53, nome: "Gato",      tipo: "normal",   vida: 3500, ataque: 570, arma: "Arranhão",           super: "Miado Poderoso",    efeito: "rapido",   superDano: 1400, velocidade: 1.2,  cor: "#CFD8DC" },
  { id: 54, nome: "Raio",      tipo: "eletrico", vida: 3100, ataque: 680, arma: "Arco Elétrico",      super: "Relâmpago Final",   efeito: "dano",     superDano: 1850, velocidade: 1.2,  cor: "#FFEB3B" },
  { id: 55, nome: "Fogueira",  tipo: "fogo",     vida: 4400, ataque: 580, arma: "Tocha Dupla",        super: "Incêndio Total",    efeito: "explosao", superDano: 1750, velocidade: 1.0,  cor: "#BF360C" },
  { id: 56, nome: "Golfinho",  tipo: "agua",     vida: 3900, ataque: 560, arma: "Onda Sônica",        super: "Maremoto",          efeito: "dano",     superDano: 1550, velocidade: 1.15, cor: "#0288D1" },
  { id: 57, nome: "Orquidea",  tipo: "planta",   vida: 3600, ataque: 600, arma: "Pétalas Cortantes",  super: "Perfume Mortal",    efeito: "congelar", superDano: 1450, velocidade: 1.1,  cor: "#2E7D32" },
  { id: 58, nome: "Louva",     tipo: "inseto",   vida: 3400, ataque: 650, arma: "Foices Verdes",      super: "Dança da Morte",    efeito: "rapido",   superDano: 1650, velocidade: 1.25, cor: "#827717" },
  { id: 59, nome: "Escorpiao", tipo: "venenoso", vida: 4800, ataque: 600, arma: "Cauda Venenosa",     super: "Ferrão Final",      efeito: "dano",     superDano: 1700, velocidade: 1.0,  cor: "#6A1B9A" },
  { id: 60, nome: "Aurora",    tipo: "gelo",     vida: 3500, ataque: 590, arma: "Aurora Boreal",      super: "Era do Gelo",       efeito: "congelar", superDano: 1600, velocidade: 1.05, cor: "#00BCD4" },
  { id: 61, nome: "Polter",    tipo: "fantasma", vida: 3600, ataque: 620, arma: "Objetos Voadores",   super: "Casa Mal-Assombrada", efeito: "dano",   superDano: 1650, velocidade: 1.05, cor: "#4527A0" },
  { id: 62, nome: "Cupido",    tipo: "fada",     vida: 3200, ataque: 610, arma: "Arco do Amor",       super: "Flechada Mágica",   efeito: "dano",     superDano: 1650, velocidade: 1.15, cor: "#E91E63" },
  { id: 63, nome: "Tirano",    tipo: "dragao",   vida: 6500, ataque: 720, arma: "Mandíbula Dracônica",super: "Extinção",          efeito: "explosao", superDano: 2500, velocidade: 0.9,  cor: "#8E0000" },
  { id: 64, nome: "Lenda",     tipo: "normal",   vida: 5500, ataque: 650, arma: "Espada Lendária",    super: "Golpe Lendário",    efeito: "dano",     superDano: 2000, velocidade: 1.05, cor: "#FFD700" },
];

// Multiplicador simples de tipo (vantagem clássica estilo pedra-papel-tesoura elemental)
const VANTAGEM = {
  eletrico: ["agua", "voador"],
  fogo: ["planta", "inseto", "gelo", "aco"],
  agua: ["fogo", "terrestre", "pedra"],
  planta: ["agua", "terrestre", "pedra"],
  inseto: ["planta", "psiquico", "sombrio"],
  venenoso: ["planta", "fada"],
  gelo: ["planta", "voador", "terrestre", "dragao"],
  fantasma: ["fantasma", "psiquico"],
  fada: ["lutador", "dragao", "sombrio"],
  dragao: ["dragao"],
  aco: ["gelo", "pedra", "fada"],
  voador: ["planta", "inseto", "lutador"],
  psiquico: ["lutador", "venenoso"],
  terrestre: ["eletrico", "fogo", "pedra", "aco", "venenoso"],
  pedra: ["fogo", "gelo", "voador", "inseto"],
  sombrio: ["fantasma", "psiquico"],
  lutador: ["normal", "gelo", "pedra", "aco", "sombrio"],
  normal: [],
};

function multiplicadorTipo(atacante, defensor) {
  if ((VANTAGEM[atacante] || []).includes(defensor)) return 1.5;
  return 1.0;
}

// Missões: completar libera troféus e novos brawlers
const MISSOES = [
  { id: "m1", nome: "Vença 1 partida", desc: "Vença qualquer modo", meta: 1, trofeus: 5 },
  { id: "m2", nome: "Artilheiro", desc: "Marque 3 gols no Futebol", meta: 3, trofeus: 6 },
  { id: "m3", nome: "Sobrevivente", desc: "Vença 2x a Sobrevivência", meta: 2, trofeus: 6 },
  { id: "m4", nome: "Caçador de Gemas", desc: "Colete 20 gemas no Pique-Gema", meta: 20, trofeus: 6 },
  { id: "m5", nome: "Poder Total", desc: "Use 5 poderes especiais", meta: 5, trofeus: 5 },
  { id: "m6", nome: "Derrotista", desc: "Derrote 15 inimigos", meta: 15, trofeus: 7 },
];
